### ISSUE TITLE
No devices after adding successfully 

### ISSUE THREAD

**Issue by BloodSeaker** [barleybobs/homeassistant-ecowater-softener#66]
Hi

I just added my ecowater system using this plugin.
Adding it went fine and it said it was added successfully.
However it states 'no devices or entities' in the detail screen.
I checked the logs but it seems not easy to know what logs are for which p'ugin actually. I see a network unreachable but that is unrelated to the setup as it occurred before as well and is relating to dlna stuff. Don't see any other errors

**Comment by NickBottelare** [comment]
Hi Bloodseaker and all,

I have exactly the same issue since I had to re-install the integration, no devices or entities.

I observed that I get the success message even when I fill in the wrong password. So now I make sure the password I fill in is the one I use to login at wifi.ecowater.com, but still no devices/entities.

Anyone has a clue what's going wrong?

Cheers,

Nick

**Comment by barleybobs** [comment]
@BloodSeaker did you manage to get the device to add successfully?

**Comment by BloodSeaker** [comment]
No, unfortunately no sensors are added

**Comment by barleybobs** [comment]
Have you updated to v3.4.1 and if the error is still occurring are there any issues in the log?

**Comment by BloodSeaker** [comment]
I have everything running on latest version.
I removed the device, took the plug out for several minutes, re-added it.
It was then re-added without warnings but no sensors are showing up

**Comment by barleybobs** [comment]
Odd, it's hard to decipher why the issue is occurring. My device is working and there are no errors.

**Comment by srempfer** [comment]
I've the same issue with the version 4.1.0 running on HA 2024.10.0
Found the following error in the logs:
```
2024-10-03 16:16:03.096 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up ecowater_softener platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 628, in async_add_entities
    for entity in new_entities:
  File "/config/custom_components/ecowater_softener/sensor.py", line 162, in <genexpr>
    EcowaterSensor(coordinator, description, config['device_serial_number'])
  File "/config/custom_components/ecowater_softener/sensor.py", line 188, in __init__
    self._attr_native_value = getattr(self.coordinator.data, self.entity_description.key)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/ecowater_softener/ecowater.py", line 62, in current_water_flow
    return self.get_property_value("current_water_flow_gpm") / 10
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```
Maybe that helps to find the root cause

**Comment by srempfer** [comment]
**Update:** 
After some days I reloaded the integration and now it works. My guess is that the API was not yet ready to or not yet served the 'current_water_flow_gpm' property.

![image](https://github.com/user-attachments/assets/becdd03b-7af2-478e-9168-d5435bceb938)

**Comment by andygatenby** [comment]
I installed the integration today, put in my user and password and it also told me I have no available devices to configure, yet I can attach using their android app and see data just fine. I loogged out of the android app and tried again thinking maybe they only allowed one login but it still didn't work. I'm using homeassistant green. I couldn't see anything in the logs. The only visible device or service is under the HACS device and it is an ecowater configuration update thing. Have no idea how to proceed.

**Comment by eg0170** [comment]
See #81
